image_folder: samples/apple
image_size: 224
ckpt: co3d_model0.pth


MODEL:
    _target_: models.PoseDiffusionModel

    pose_encoding: absT_quaR_logFL

    IMG_FEATURE_EXTRACTOR: 
        _target_: models.ImageFeatureExtractor
        freeze: False

    DENOISER: 
        _target_: models.Denoiser
        TRANSFORMER:
            _target_:               torch.nn.Transformer
            d_model:                512
            nhead:                  4
            dim_feedforward:        1024
            num_encoder_layers:     2
            num_decoder_layers:     6
            dropout:                0.1
            batch_first:            True
            norm_first:             True


    DIFFUSER:
        _target_: models.GaussianDiffusion
        beta_schedule: custom
