MODEL:
    _target_: models.PoseDiffusionModel


    Img_Feature_Extractor: 
        _target_: models.ImageGlobalPredictor
        multiscale: True
        freeze: False

    DENOISER: 
        _target_: models.Denoiser

    DIFFUSER:
        _target_: models.GaussianDiffusion
        beta_schedule: custom
        

TEST:
    image_folder: samples/apple
    image_size: 224

