Model:
    _target_: models.PoseDiffusionModel


    Img_model: 
        _target_: models.ImageGlobalPredictor
        multiscale: True

    Denoiser: 
        _target_: models.Denoiser

        # Transformer
        
        num_decoder_layers: 2
        num_encoder_layers: 2
        nhead: 4


    #     _target_: SimpleTransformer

    #     num_encoders: 2
    #     num_decoders: 6

    #     mlps: 
    #         mlp_layer: [[512, 256], [256, 128]]
