Model:
    _target_: models.PoseDiffusionModel


    Img_model: 
        _target_: models.ImageGlobalPredictor
        multiscale: True

    Denoiser: 
        name: debug



    #     _target_: SimpleTransformer

    #     num_encoders: 2
    #     num_decoders: 6

    #     mlps: 
    #         mlp_layer: [[512, 256], [256, 128]]
